name: Renovate

on:
  schedule:
    - cron: "0 14 * * 5" # e.g: Every friday afternoon

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate Automatic Branch
        uses: bodinsamuel/renovate-automatic-branch@v1
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          repo-owner: ${{ github.repository_owner }}
          repo-name: ${{ github.event.repository.name }}
